camunda.bpm.admin-user:
  id: demo
  password: demo

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:camunda-h2-database-main;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name:
    username: sa
    password:
    hikari:
      auto-commit: false
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true

server:
  port: 8282

logging:
  level:
    root: debug
